# Generated by Django 6.0.2 on 2026-03-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_route', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='address',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='truckstop_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
