# Generated by Django 6.0.2 on 2026-03-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_route', '0002_fuelstation_address_fuelstation_truckstop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='price',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
    ]
